# Changes here will be overwritten by Copier
_commit: c124449
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: python-project-templates
project_description: Hatch plugin for JavaScript
project_name: hatch javascript
python_version_primary: '3.11'
team: the hatch-javascript authors
